export const SEARCH_FLIGHT = "SEARCH_FLIGHT";
export const SEARCH_HOTEL = "SEARCH_HOTEL";
export const BOOKING_HOTEL = "BOOKING_HOTEL";
export const PASSENGER_INFO_DETAILS = "PASSENGER_INFO_DETAILS";
export const KTP = "KTP";
export const KITAS = "KITAS";
export const KIA = "KIA";
export const KK = "KK";
export const TIME_OUT_API = 60000;
export const TIME_OUT_NONTRANSACTIONAL = 30000;
export const ERROR_CODE_GENERAL_NETWORK = "CLICKS : 0020";
export const ERROR_CODE_BOOKING_INTEGRATOR_NO_SEAT =
  "BOOKING_INTEGRATOR_NO_SEAT";
